// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package hestia

import (
	"database/sql"
)

type Todo struct {
	ID          int64
	Title       string
	Description sql.NullString
	Priority    sql.NullInt32
	State       sql.NullString
	CreatedAt   interface{}
	FinishedAt  interface{}
	Responsible sql.NullString
}

type Todolist struct {
	ID        int64
	Name      string
	CreatedAt interface{}
}
